name: Step 2. Init terraform remote backend

on:
  # push:
  #   branches: ["main", "dev"]
  workflow_dispatch:  # running manually
    inputs:
      ycloud_region:
        default: ru-central1
        description: YCloud region
        type: choice
        required: true
        options:
        - ru-central1
      dynamodb_table_name:
        default: lock
        description: Таблица для хранения состояния
        type: string
        required: true

jobs:
  # Создаю таблицу для хранения состояния
  dynamodb-init:
    name: Create table into DynamoDB
    runs-on: ubuntu-latest
    needs: terraform-init

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: execute py script # run main.py
      run: | 
        python scripts/dynamodb_init.py \
          -a '${{ vars.AWS_ACCESS_KEY }}' \
          -s '${{ secrets.AWS_SECRET_KEY }}'
      env:
        TABLE_NAME: ${{ inputs.dynamodb_table_name }}
        DOCUMENT_API_ENDPOINT: ${{ vars.DYNAMODB_API_ENDPOINT }}
        REGION_NAME: ${{ inputs.ycloud_region }}
